//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mioto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCCD
    {
        public int IDCCCD { get; set; }
        public string SoCCCD { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string HinhAnh { get; set; }
        public string TrangThai { get; set; }
        public int IDKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
