//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mioto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhiHuyChuyen
    {
        public int IDHC { get; set; }
        public int LoaiHuyChuyen { get; set; }
        public System.DateTime ThoiGianHuy { get; set; }
        public string MoTa { get; set; }
        public decimal SoTienHoan { get; set; }
        public int IDDT { get; set; }
    
        public virtual DonThueXe DonThueXe { get; set; }
    }
}
