//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mioto.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChinhSachChietKhau
    {
        public int IDCSC { get; set; }
        public int IDCX { get; set; }
        public int LoaiThoiGian { get; set; }
        public decimal PhanTramGiam { get; set; }
    
        public virtual ChuXe ChuXe { get; set; }
    }
}
