//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mioto.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuXe()
        {
            this.ChinhSachChietKhau = new HashSet<ChinhSachChietKhau>();
            this.DoanhThuChuXe = new HashSet<DoanhThuChuXe>();
            this.Xe = new HashSet<Xe>();
        }
    
        public int IDCX { get; set; }
        public string Ten { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string SoGPLX { get; set; }
        public string MatKhau { get; set; }
        public string CCCD { get; set; }
        public string GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string HinhAnh { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> IDKH { get; set; }
    
        public virtual CCCD CCCD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChinhSachChietKhau> ChinhSachChietKhau { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoanhThuChuXe> DoanhThuChuXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xe> Xe { get; set; }
    }
}
