//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mioto.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPLX
    {
        public int IDGPLX { get; set; }
        public string SoGPLX { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string HinhAnh { get; set; }
        public string TrangThai { get; set; }
        public int IDKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
