//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mioto.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int IDTT { get; set; }
        public int IDDT { get; set; }
        public string PhuongThuc { get; set; }
        public System.DateTime NgayTT { get; set; }
        public decimal SoTien { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> IDMGG { get; set; }
    
        public virtual DonThueXe DonThueXe { get; set; }
        public virtual MaGiamGia MaGiamGia { get; set; }
    }
}
